import { Tour } from '@/types/onboarding';

export const ONBOARDING_TOURS: Tour[] = [
  {
    id: 'dashboard',
    name: 'Visão Geral',
    description: 'Conheça o painel principal e os KPIs do seu negócio',
    icon: 'LayoutDashboard',
    estimatedTime: '3 min',
    requiredRoute: '/admin',
    steps: [
      {
        id: 'dashboard-1',
        targetSelector: '[data-tour="dashboard-header"]',
        title: 'Bem-vindo ao Dashboard',
        content: 'Este é seu painel principal. Aqui você vê todos os indicadores do seu negócio em tempo real.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'dashboard-2',
        targetSelector: '[data-tour="kpi-total-agendamentos"]',
        title: 'Total de Agendamentos',
        content: 'Total de agendamentos do período selecionado. O badge verde/vermelho mostra a variação em relação ao período anterior.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'dashboard-3',
        targetSelector: '[data-tour="kpi-receita"]',
        title: 'Receita Realizada',
        content: 'Receita realizada e prevista. Acompanhe o faturamento do seu negócio.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'dashboard-4',
        targetSelector: '[data-tour="period-filter"]',
        title: 'Filtro de Período',
        content: 'Use este filtro para alterar o período de análise: hoje, semana, mês ou máximo.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'dashboard-5',
        targetSelector: '[data-tour="chart-agendamentos"]',
        title: 'Gráfico de Evolução',
        content: 'Gráfico de evolução de agendamentos. Veja tendências e sazonalidade do seu negócio.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'dashboard-6',
        targetSelector: '[data-tour="top-bairros"]',
        title: 'Top Bairros',
        content: 'Ranking dos bairros com mais agendamentos. Identifique suas regiões mais lucrativas.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'dashboard-7',
        targetSelector: '[data-tour="top-servicos"]',
        title: 'Top Serviços',
        content: 'Serviços mais solicitados pelos clientes. Use para criar promoções direcionadas.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  {
    id: 'agendamentos',
    name: 'Gestão de Agendamentos',
    description: 'Aprenda a gerenciar agendamentos do início ao fim',
    icon: 'CalendarDays',
    estimatedTime: '5 min',
    requiredRoute: '/admin/agendamentos',
    steps: [
      {
        id: 'agendamentos-1',
        targetSelector: '[data-tour="novo-agendamento"]',
        title: 'Novo Agendamento',
        content: 'Clique aqui para criar um agendamento manual quando um cliente ligar ou enviar mensagem.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'agendamentos-2',
        targetSelector: '[data-tour="stats-header"]',
        title: 'Estatísticas Rápidas',
        content: 'Cards de estatísticas: veja agendamentos de hoje, da semana e do mês em um relance.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'agendamentos-3',
        targetSelector: '[data-tour="filters"]',
        title: 'Filtros de Busca',
        content: 'Use os filtros para buscar por nome, telefone, status ou período específico.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'agendamentos-4',
        targetSelector: '[data-tour="bulk-actions"]',
        title: 'Ações em Massa',
        content: 'Selecione múltiplos agendamentos para alterar status em massa ou exportar.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'agendamentos-5',
        targetSelector: '[data-tour="export-excel"]',
        title: 'Exportar Dados',
        content: 'Exporte seus dados para Excel ou PDF para análises externas ou relatórios.',
        action: 'view',
        position: 'left',
      },
    ],
  },
  {
    id: 'tecnicos',
    name: 'Gestão de Técnicos',
    description: 'Gerencie sua equipe de técnicos e atribuições',
    icon: 'Users',
    estimatedTime: '4 min',
    requiredRoute: '/admin/tecnicos',
    steps: [
      {
        id: 'tecnicos-1',
        targetSelector: '[data-tour="adicionar-tecnico"]',
        title: 'Adicionar Técnico',
        content: 'Adicione novos técnicos à sua equipe. Eles receberão acesso ao app de serviços.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'tecnicos-2',
        targetSelector: '[data-tour="kpi-tecnicos"]',
        title: 'KPIs da Equipe',
        content: 'Visualize métricas importantes: total de técnicos ativos e serviços agendados para hoje.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'tecnicos-3',
        targetSelector: '[data-tour="buscar-tecnico"]',
        title: 'Buscar Técnico',
        content: 'Busque técnicos por nome, email ou telefone rapidamente.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'tecnicos-4',
        targetSelector: '[data-tour="tecnico-card"]',
        title: 'Card do Técnico',
        content: 'Cada card mostra: foto, nome, telefone e quantos serviços o técnico tem hoje.',
        action: 'view',
        position: 'right',
      },
    ],
  },
  {
    id: 'financeiro',
    name: 'Controle Financeiro',
    description: 'Acompanhe receitas, despesas e saldo',
    icon: 'DollarSign',
    estimatedTime: '4 min',
    requiredRoute: '/admin/financeiro',
    steps: [
      {
        id: 'financeiro-1',
        targetSelector: '[data-tour="kpi-receita-mensal"]',
        title: 'Receita Mensal',
        content: 'Receita do mês atual. Compare com o mês anterior pelo indicador de tendência.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'financeiro-2',
        targetSelector: '[data-tour="kpi-despesa-mensal"]',
        title: 'Despesa Mensal',
        content: 'Despesas do mês. Monitore para manter a margem saudável.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'financeiro-3',
        targetSelector: '[data-tour="kpi-saldo"]',
        title: 'Saldo',
        content: 'Saldo: diferença entre receitas e despesas. Verde = lucro, vermelho = prejuízo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'financeiro-4',
        targetSelector: '[data-tour="chart-evolucao"]',
        title: 'Evolução Mensal',
        content: 'Gráfico de evolução mensal. Identifique tendências ao longo do tempo.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'financeiro-5',
        targetSelector: '[data-tour="historico-transacoes"]',
        title: 'Histórico de Transações',
        content: 'Últimas transações registradas. Clique para ver detalhes.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing e Conversão',
    description: 'Acompanhe funil de vendas e conversões',
    icon: 'Megaphone',
    estimatedTime: '3 min',
    requiredRoute: '/admin/marketing',
    steps: [
      {
        id: 'marketing-1',
        targetSelector: '[data-tour="kpi-leads"]',
        title: 'Total de Leads',
        content: 'Total de leads captados. Cada visitante que inicia o checkout é um lead.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'marketing-2',
        targetSelector: '[data-tour="kpi-taxa-conversao"]',
        title: 'Taxa de Conversão',
        content: 'Taxa de conversão: percentual de leads que viraram clientes pagantes.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'marketing-3',
        targetSelector: '[data-tour="funil"]',
        title: 'Funil de Conversão',
        content: 'Funil de conversão: visualize cada etapa da jornada do cliente.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'marketing-4',
        targetSelector: '[data-tour="leads-por-canal"]',
        title: 'Leads por Canal',
        content: 'Veja quais canais (Google, Instagram, WhatsApp) trazem mais leads.',
        action: 'view',
        position: 'left',
      },
    ],
  },
  {
    id: 'relatorios',
    name: 'Relatórios',
    description: 'Análises detalhadas do negócio',
    icon: 'BarChart3',
    estimatedTime: '3 min',
    requiredRoute: '/admin/relatorios',
    steps: [
      {
        id: 'relatorios-1',
        targetSelector: '[data-tour="top-bairros-table"]',
        title: 'Top Bairros',
        content: 'Tabela completa com ranking de bairros: quantidade, receita e ticket médio.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'relatorios-2',
        targetSelector: '[data-tour="top-itens-table"]',
        title: 'Top Itens',
        content: 'Itens mais orçados pelos clientes. Use para definir promoções.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'relatorios-3',
        targetSelector: '[data-tour="analise-genero"]',
        title: 'Análise por Gênero',
        content: 'Distribuição por gênero (identificado automaticamente). Entenda seu público.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  {
    id: 'integracoes',
    name: 'Integrações',
    description: 'Configure automações e integrações',
    icon: 'Plug',
    estimatedTime: '4 min',
    requiredRoute: '/admin/integracoes/whatsapp',
    steps: [
      {
        id: 'integracoes-1',
        targetSelector: '[data-tour="adicionar-numero"]',
        title: 'Adicionar WhatsApp',
        content: 'Conecte seu WhatsApp Business para automações de mensagens.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'integracoes-2',
        targetSelector: '[data-tour="whatsapp-status"]',
        title: 'Status da Conexão',
        content: 'Status da conexão: verde = conectado e operacional.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'integracoes-3',
        targetSelector: '[data-tour="auto-confirmacao"]',
        title: 'Confirmação Automática',
        content: 'Ative para enviar confirmação automática ao criar agendamento.',
        action: 'view',
        position: 'left',
      },
      {
        id: 'integracoes-4',
        targetSelector: '[data-tour="lembrete-24h"]',
        title: 'Lembrete 24h',
        content: 'Lembrete 24h: cliente recebe mensagem automática um dia antes.',
        action: 'view',
        position: 'left',
      },
      {
        id: 'integracoes-5',
        targetSelector: '[data-tour="salvar-configs"]',
        title: 'Salvar Configurações',
        content: 'Sempre salve após fazer alterações nas configurações.',
        action: 'click',
        position: 'top',
      },
    ],
  },
];

export const getTourById = (id: string): Tour | undefined => {
  return ONBOARDING_TOURS.find(tour => tour.id === id);
};

export const getTourIcon = (iconName: string) => {
  const icons: Record<string, string> = {
    LayoutDashboard: 'LayoutDashboard',
    CalendarDays: 'CalendarDays',
    Users: 'Users',
    DollarSign: 'DollarSign',
    Megaphone: 'Megaphone',
    BarChart3: 'BarChart3',
    Plug: 'Plug',
  };
  return icons[iconName] || 'Circle';
};
