import { Tour } from '@/types/onboarding';

/**
 * Tours por Tela - Sistema de Onboarding Contextual
 * Cada tela tem seu próprio tour que é executado na primeira visita
 */

export const SCREEN_TOURS: Tour[] = [
  // ═══════════════════════════════════════════════════
  // MÓDULO PRINCIPAL
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-live-view',
    name: 'Live View',
    description: 'Monitoramento em tempo real',
    icon: 'Activity',
    estimatedTime: '2 min',
    requiredRoute: '/admin/live-view',
    steps: [
      {
        id: 'live-1',
        targetSelector: '[data-tour="live-badge"]',
        title: 'Dados em Tempo Real',
        content: 'Os dados são atualizados automaticamente a cada poucos segundos. O badge pulsante indica que está ao vivo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'live-2',
        targetSelector: '[data-tour="live-visitors"]',
        title: 'Visitantes Agora',
        content: 'Quantidade de pessoas navegando no site neste exato momento.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'live-3',
        targetSelector: '[data-tour="live-carts"]',
        title: 'Carrinhos Ativos',
        content: 'Clientes com itens no carrinho. Oportunidade de conversão em tempo real!',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'live-4',
        targetSelector: '[data-tour="live-revenue"]',
        title: 'Receita do Dia',
        content: 'Receita gerada hoje, atualizada em tempo real a cada nova venda.',
        action: 'view',
        position: 'bottom',
      },
    ],
  },
  
  {
    id: 'screen-tracking',
    name: 'Histórico de Tracking',
    description: 'Rastreamento de técnicos',
    icon: 'MapPin',
    estimatedTime: '2 min',
    requiredRoute: '/admin/tracking',
    steps: [
      {
        id: 'tracking-1',
        targetSelector: '[data-tour="tracking-header"]',
        title: 'Histórico de Rastreamento',
        content: 'Acompanhe trajetos e pontualidade dos técnicos em campo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'tracking-2',
        targetSelector: '[data-tour="tracking-period"]',
        title: 'Filtro de Período',
        content: 'Selecione o período para análise: 7 dias, 30 dias ou período personalizado.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'tracking-3',
        targetSelector: '[data-tour="tracking-kpis"]',
        title: 'Métricas de Tracking',
        content: 'Veja distância total percorrida, tempo médio e taxa de pontualidade.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'tracking-4',
        targetSelector: '[data-tour="tracking-optimizer"]',
        title: 'Otimizador de Rotas',
        content: 'Sugere a melhor sequência de visitas para economizar tempo e combustível.',
        action: 'view',
        position: 'right',
      },
    ],
  },
  
  {
    id: 'screen-ajuda',
    name: 'Central de Ajuda',
    description: 'Documentação e manual',
    icon: 'HelpCircle',
    estimatedTime: '1 min',
    requiredRoute: '/admin/ajuda',
    steps: [
      {
        id: 'ajuda-1',
        targetSelector: '[data-tour="ajuda-search"]',
        title: 'Buscar no Manual',
        content: 'Digite para buscar qualquer funcionalidade no manual completo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'ajuda-2',
        targetSelector: '[data-tour="ajuda-tabs"]',
        title: 'Seções do Manual',
        content: 'Manual completo, boas práticas e erros comuns com soluções.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'ajuda-3',
        targetSelector: '[data-tour="ajuda-download"]',
        title: 'Baixar PDF',
        content: 'Baixe o manual completo em PDF para consulta offline.',
        action: 'click',
        position: 'left',
      },
    ],
  },

  // ═══════════════════════════════════════════════════
  // MÓDULO MARKETING
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-carrinhos',
    name: 'Carrinhos Abandonados',
    description: 'Recuperação de vendas',
    icon: 'ShoppingCart',
    estimatedTime: '2 min',
    requiredRoute: '/admin/carrinhos-abandonados',
    steps: [
      {
        id: 'carrinhos-1',
        targetSelector: '[data-tour="carrinhos-total"]',
        title: 'Total de Carrinhos',
        content: 'Total de carrinhos abandonados no sistema. Cada um é uma oportunidade de venda.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'carrinhos-2',
        targetSelector: '[data-tour="carrinhos-recuperacao"]',
        title: 'Taxa de Recuperação',
        content: 'Percentual de carrinhos recuperados com sucesso via automação.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'carrinhos-3',
        targetSelector: '[data-tour="carrinhos-valor"]',
        title: 'Valor em Risco',
        content: 'Receita potencial que pode ser recuperada com ações de follow-up.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'carrinhos-4',
        targetSelector: '[data-tour="carrinhos-automacao"]',
        title: 'Automação Ativa',
        content: 'WhatsApp enviado automaticamente 2 minutos após abandono.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'carrinhos-5',
        targetSelector: '[data-tour="carrinhos-tabs"]',
        title: 'Filtrar por Status',
        content: 'Filtre por: abandonado, contatado, recuperado ou convertido.',
        action: 'click',
        position: 'bottom',
      },
    ],
  },
  
  {
    id: 'screen-cupons',
    name: 'Cupons de Desconto',
    description: 'Gestão de cupons promocionais',
    icon: 'Tag',
    estimatedTime: '2 min',
    requiredRoute: '/admin/cupons',
    steps: [
      {
        id: 'cupons-1',
        targetSelector: '[data-tour="cupons-novo"]',
        title: 'Criar Cupom',
        content: 'Crie códigos promocionais para suas campanhas de marketing.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'cupons-2',
        targetSelector: '[data-tour="cupons-ativos"]',
        title: 'Cupons Ativos',
        content: 'Quantidade de cupons ativos no momento.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'cupons-3',
        targetSelector: '[data-tour="cupons-usos"]',
        title: 'Total de Usos',
        content: 'Quantas vezes os cupons foram utilizados pelos clientes.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'cupons-4',
        targetSelector: '[data-tour="cupons-tabela"]',
        title: 'Lista de Cupons',
        content: 'Todos os cupons com código, desconto, validade e status.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-templates',
    name: 'Templates WhatsApp',
    description: 'Modelos de mensagem',
    icon: 'MessageSquare',
    estimatedTime: '2 min',
    requiredRoute: '/admin/templates',
    steps: [
      {
        id: 'templates-1',
        targetSelector: '[data-tour="templates-novo"]',
        title: 'Novo Template',
        content: 'Crie modelos de mensagem para WhatsApp com variáveis dinâmicas.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'templates-2',
        targetSelector: '[data-tour="templates-busca"]',
        title: 'Buscar Templates',
        content: 'Pesquise templates por nome ou conteúdo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'templates-3',
        targetSelector: '[data-tour="templates-categoria"]',
        title: 'Filtrar por Categoria',
        content: 'Filtre por tipo: agendamento, carrinho, pós-venda, cobrança.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'templates-4',
        targetSelector: '[data-tour="templates-card"]',
        title: 'Card do Template',
        content: 'Visualize preview, status e ações disponíveis para cada template.',
        action: 'view',
        position: 'right',
      },
    ],
  },
  
  {
    id: 'screen-push',
    name: 'Push Notifications',
    description: 'Notificações push',
    icon: 'Bell',
    estimatedTime: '2 min',
    requiredRoute: '/admin/push-notifications',
    steps: [
      {
        id: 'push-1',
        targetSelector: '[data-tour="push-testar"]',
        title: 'Testar Notificação',
        content: 'Envie uma notificação de teste para seu dispositivo.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'push-2',
        targetSelector: '[data-tour="push-dispositivos"]',
        title: 'Dispositivos Cadastrados',
        content: 'Total de dispositivos que podem receber notificações push.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'push-3',
        targetSelector: '[data-tour="push-taxa"]',
        title: 'Taxa de Entrega',
        content: 'Percentual de notificações entregues com sucesso.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'push-4',
        targetSelector: '[data-tour="push-grafico"]',
        title: 'Histórico de Envios',
        content: 'Gráfico mostrando sucesso vs falhas ao longo do tempo.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-avaliacoes',
    name: 'Sistema de Avaliações',
    description: 'NPS e feedback',
    icon: 'Star',
    estimatedTime: '2 min',
    requiredRoute: '/admin/avaliacoes-config',
    steps: [
      {
        id: 'avaliacoes-1',
        targetSelector: '[data-tour="avaliacoes-config"]',
        title: 'Configurações',
        content: 'Configure link do Google Reviews e nota mínima para pedir review.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'avaliacoes-2',
        targetSelector: '[data-tour="avaliacoes-url"]',
        title: 'URL do Google Reviews',
        content: 'Cole o link do seu Google Meu Negócio para redirecionamento.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'avaliacoes-3',
        targetSelector: '[data-tour="avaliacoes-threshold"]',
        title: 'Nota Mínima',
        content: 'Clientes com nota acima deste valor são convidados a avaliar no Google.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'avaliacoes-4',
        targetSelector: '[data-tour="avaliacoes-feedbacks"]',
        title: 'Ver Feedbacks',
        content: 'Visualize todas as avaliações recebidas dos clientes.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-canais',
    name: 'Canais de Origem',
    description: 'Rastreamento de tráfego',
    icon: 'Share2',
    estimatedTime: '2 min',
    requiredRoute: '/admin/integracoes/canais',
    steps: [
      {
        id: 'canais-1',
        targetSelector: '[data-tour="canais-novo"]',
        title: 'Novo Canal',
        content: 'Crie um canal para cada fonte de tráfego: Instagram, TikTok, Google, etc.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'canais-2',
        targetSelector: '[data-tour="canais-cliques"]',
        title: 'Total de Cliques',
        content: 'Cliques totais em todos os canais de origem.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'canais-3',
        targetSelector: '[data-tour="canais-conversoes"]',
        title: 'Conversões',
        content: 'Quantos cliques se transformaram em vendas efetivas.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'canais-4',
        targetSelector: '[data-tour="canais-copiar"]',
        title: 'Copiar Link',
        content: 'Copie o link de rastreamento para usar em suas redes sociais.',
        action: 'click',
        position: 'left',
      },
    ],
  },

  // ═══════════════════════════════════════════════════
  // MÓDULO BLOG/SEO
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-blog',
    name: 'Dashboard Blog',
    description: 'Métricas SEO',
    icon: 'FileText',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog',
    steps: [
      {
        id: 'blog-1',
        targetSelector: '[data-tour="blog-keywords-total"]',
        title: 'Keywords Mapeadas',
        content: 'Total de keywords no seu banco para geração de conteúdo.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'blog-2',
        targetSelector: '[data-tour="blog-oportunidade"]',
        title: 'Alta Oportunidade',
        content: 'Keywords com score ≥ 80. Priorize estas para gerar posts!',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'blog-3',
        targetSelector: '[data-tour="blog-publicados"]',
        title: 'Posts Publicados',
        content: 'Artigos já publicados no WordPress.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'blog-4',
        targetSelector: '[data-tour="blog-top-keywords"]',
        title: 'Top Keywords',
        content: 'Ranking das melhores keywords para gerar conteúdo.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-blog-gerar',
    name: 'Gerar Posts',
    description: 'Criação com IA',
    icon: 'Sparkles',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog/gerar',
    steps: [
      {
        id: 'gerar-1',
        targetSelector: '[data-tour="gerar-filtros"]',
        title: 'Filtros de Keywords',
        content: 'Filtre keywords por cluster, cidade, funil de conversão.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'gerar-2',
        targetSelector: '[data-tour="gerar-top"]',
        title: 'Seleção Rápida',
        content: 'Selecione rapidamente Top 5 ou Top 10 keywords.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'gerar-3',
        targetSelector: '[data-tour="gerar-lista"]',
        title: 'Lista de Keywords',
        content: 'Clique para selecionar. O checkbox marca sua escolha.',
        action: 'click',
        position: 'right',
      },
      {
        id: 'gerar-4',
        targetSelector: '[data-tour="gerar-botao"]',
        title: 'Gerar Posts',
        content: 'Inicia a geração em lote. A barra de progresso mostrará o avanço.',
        action: 'click',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-blog-fila',
    name: 'Fila e Revisão',
    description: 'Aprovar e publicar',
    icon: 'ListChecks',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog/fila',
    steps: [
      {
        id: 'fila-1',
        targetSelector: '[data-tour="fila-tabs"]',
        title: 'Filtrar por Status',
        content: 'Filtre por: gerado, revisado, pronto para publicar, publicado.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'fila-2',
        targetSelector: '[data-tour="fila-preview"]',
        title: 'Visualizar Post',
        content: 'Clique no ícone de olho para ver o preview do post.',
        action: 'click',
        position: 'left',
      },
      {
        id: 'fila-3',
        targetSelector: '[data-tour="fila-aprovar"]',
        title: 'Aprovar Post',
        content: 'Clique no check verde para aprovar o post para publicação.',
        action: 'click',
        position: 'left',
      },
      {
        id: 'fila-4',
        targetSelector: '[data-tour="fila-publicar"]',
        title: 'Publicar no WordPress',
        content: 'Publique diretamente no WordPress com um clique.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-blog-keywords',
    name: 'Banco de Keywords',
    description: 'Repositório SEO',
    icon: 'Database',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog/keywords',
    steps: [
      {
        id: 'keywords-1',
        targetSelector: '[data-tour="keywords-filtros"]',
        title: 'Filtros Avançados',
        content: 'Filtre por cluster, cidade, funil, dificuldade e oportunidade.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'keywords-2',
        targetSelector: '[data-tour="keywords-score"]',
        title: 'Score de Oportunidade',
        content: 'Quanto maior o score, melhor a oportunidade de ranqueamento.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'keywords-3',
        targetSelector: '[data-tour="keywords-dificuldade"]',
        title: 'Dificuldade',
        content: 'Verde = fácil ranquear, vermelho = competição alta.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'keywords-4',
        targetSelector: '[data-tour="keywords-exportar"]',
        title: 'Exportar Keywords',
        content: 'Exporte para CSV para análise externa.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-blog-importar',
    name: 'Importar Keywords',
    description: 'Upload de CSV',
    icon: 'Upload',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog/importar',
    steps: [
      {
        id: 'importar-1',
        targetSelector: '[data-tour="importar-dropzone"]',
        title: 'Área de Upload',
        content: 'Arraste seu arquivo CSV do Google Keyword Planner aqui.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'importar-2',
        targetSelector: '[data-tour="importar-preview"]',
        title: 'Preview das Keywords',
        content: 'Revise as keywords antes de importar para o banco.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'importar-3',
        targetSelector: '[data-tour="importar-confirmar"]',
        title: 'Confirmar Importação',
        content: 'Keywords serão classificadas automaticamente por cluster e intent.',
        action: 'click',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-blog-config',
    name: 'Configurações Blog',
    description: 'Integração WordPress',
    icon: 'Settings',
    estimatedTime: '2 min',
    requiredRoute: '/admin/blog/configuracoes',
    steps: [
      {
        id: 'blogconfig-1',
        targetSelector: '[data-tour="blogconfig-url"]',
        title: 'URL do WordPress',
        content: 'Insira a URL do seu site WordPress para integração.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'blogconfig-2',
        targetSelector: '[data-tour="blogconfig-user"]',
        title: 'Usuário e Senha',
        content: 'Use Application Password do WordPress, não a senha normal.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'blogconfig-3',
        targetSelector: '[data-tour="blogconfig-testar"]',
        title: 'Testar Conexão',
        content: 'Teste a conexão antes de publicar posts.',
        action: 'click',
        position: 'right',
      },
      {
        id: 'blogconfig-4',
        targetSelector: '[data-tour="blogconfig-qualidade"]',
        title: 'Padrões de Qualidade',
        content: 'Defina mínimo de palavras, H2s e FAQs por post.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-blog-logs',
    name: 'Logs de Publicação',
    description: 'Histórico e debug',
    icon: 'ScrollText',
    estimatedTime: '1 min',
    requiredRoute: '/admin/blog/logs',
    steps: [
      {
        id: 'logs-1',
        targetSelector: '[data-tour="logs-lista"]',
        title: 'Lista de Logs',
        content: 'Histórico de todas as execuções do pipeline de publicação.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'logs-2',
        targetSelector: '[data-tour="logs-status"]',
        title: 'Status da Execução',
        content: 'Verde = sucesso, vermelho = erro. Clique para ver detalhes.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'logs-3',
        targetSelector: '[data-tour="logs-erro"]',
        title: 'Mensagem de Erro',
        content: 'Veja a mensagem de erro para debug quando algo falhar.',
        action: 'view',
        position: 'right',
      },
    ],
  },

  // ═══════════════════════════════════════════════════
  // MÓDULO GESTÃO
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-equipe',
    name: 'Gestão de Equipe',
    description: 'Usuários e permissões',
    icon: 'Users',
    estimatedTime: '2 min',
    requiredRoute: '/admin/equipe',
    steps: [
      {
        id: 'equipe-1',
        targetSelector: '[data-tour="equipe-stats"]',
        title: 'Resumo da Equipe',
        content: 'Veja o total de membros, técnicos e funcionários bot.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'equipe-2',
        targetSelector: '[data-tour="equipe-membros"]',
        title: 'Membros do Dashboard',
        content: 'Usuários com acesso ao painel administrativo.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'equipe-3',
        targetSelector: '[data-tour="equipe-convidar"]',
        title: 'Convidar Membro',
        content: 'Convide novos membros por email com cargo específico.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'equipe-4',
        targetSelector: '[data-tour="equipe-tecnicos"]',
        title: 'Aba Técnicos',
        content: 'Gerencie a equipe técnica de campo.',
        action: 'click',
        position: 'bottom',
      },
    ],
  },
  
  {
    id: 'screen-parcerias',
    name: 'Programa de Parcerias',
    description: 'Afiliados e comissões',
    icon: 'Handshake',
    estimatedTime: '2 min',
    requiredRoute: '/admin/parcerias',
    steps: [
      {
        id: 'parcerias-1',
        targetSelector: '[data-tour="parcerias-ativos"]',
        title: 'Parceiros Ativos',
        content: 'Total de parceiros aprovados no programa.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'parcerias-2',
        targetSelector: '[data-tour="parcerias-pendentes"]',
        title: 'Pendentes',
        content: 'Parceiros aguardando aprovação.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'parcerias-3',
        targetSelector: '[data-tour="parcerias-receita"]',
        title: 'Receita via Parceiros',
        content: 'Receita total gerada pelo programa de afiliados.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'parcerias-4',
        targetSelector: '[data-tour="parcerias-conversoes"]',
        title: 'Conversões Recentes',
        content: 'Últimas vendas realizadas via parceiros.',
        action: 'click',
        position: 'left',
      },
      {
        id: 'parcerias-5',
        targetSelector: '[data-tour="parcerias-saques"]',
        title: 'Saques Pendentes',
        content: 'Solicitações de pagamento a processar.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-notas',
    name: 'Notas Fiscais',
    description: 'Emissão de NFS-e',
    icon: 'FileText',
    estimatedTime: '2 min',
    requiredRoute: '/admin/notas-fiscais',
    steps: [
      {
        id: 'notas-1',
        targetSelector: '[data-tour="notas-nova"]',
        title: 'Nova Nota Fiscal',
        content: 'Emita NFS-e para serviços realizados.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'notas-2',
        targetSelector: '[data-tour="notas-stats"]',
        title: 'KPIs de Notas',
        content: 'Veja emitidas, pendentes e canceladas do período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'notas-3',
        targetSelector: '[data-tour="notas-filtros"]',
        title: 'Filtrar Notas',
        content: 'Busque por cliente, número, status ou período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'notas-4',
        targetSelector: '[data-tour="notas-tabela"]',
        title: 'Lista de Notas',
        content: 'Visualize, baixe XML ou cancele notas fiscais.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-orcamentos',
    name: 'Orçamentos',
    description: 'Propostas comerciais',
    icon: 'Calculator',
    estimatedTime: '2 min',
    requiredRoute: '/admin/orcamentos',
    steps: [
      {
        id: 'orcamentos-1',
        targetSelector: '[data-tour="orcamentos-novo"]',
        title: 'Novo Orçamento',
        content: 'Crie propostas comerciais personalizadas.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'orcamentos-2',
        targetSelector: '[data-tour="orcamentos-stats"]',
        title: 'KPIs de Orçamentos',
        content: 'Total, aprovados, pendentes e taxa de conversão.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'orcamentos-3',
        targetSelector: '[data-tour="orcamentos-tabela"]',
        title: 'Lista de Orçamentos',
        content: 'Todos os orçamentos com status e ações.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'orcamentos-4',
        targetSelector: '[data-tour="orcamentos-detalhes"]',
        title: 'Ver Detalhes',
        content: 'Visualize orçamento completo e envie ao cliente.',
        action: 'click',
        position: 'left',
      },
    ],
  },

  // ═══════════════════════════════════════════════════
  // MÓDULO FINANCEIRO
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-consolidado',
    name: 'Consolidado Financeiro',
    description: 'Relatório mensal',
    icon: 'PieChart',
    estimatedTime: '2 min',
    requiredRoute: '/admin/financeiro/consolidado',
    steps: [
      {
        id: 'consolidado-1',
        targetSelector: '[data-tour="consolidado-periodo"]',
        title: 'Período',
        content: 'Selecione o mês para visualizar o consolidado.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'consolidado-2',
        targetSelector: '[data-tour="consolidado-resumo"]',
        title: 'Resumo do Mês',
        content: 'Receita, despesa e saldo do período selecionado.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'consolidado-3',
        targetSelector: '[data-tour="consolidado-categorias"]',
        title: 'Por Categoria',
        content: 'Distribuição de receitas e despesas por categoria.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'consolidado-4',
        targetSelector: '[data-tour="consolidado-exportar"]',
        title: 'Exportar Relatório',
        content: 'Exporte o consolidado em PDF ou Excel.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-receitas',
    name: 'Receitas',
    description: 'Controle de recebimentos',
    icon: 'TrendingUp',
    estimatedTime: '2 min',
    requiredRoute: '/admin/financeiro/receitas',
    steps: [
      {
        id: 'receitas-1',
        targetSelector: '[data-tour="receitas-esperada"]',
        title: 'Receita Esperada',
        content: 'Total previsto dos agendamentos do período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'receitas-2',
        targetSelector: '[data-tour="receitas-realizada"]',
        title: 'Receita Realizada',
        content: 'Valor efetivamente recebido (pagamentos confirmados).',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'receitas-3',
        targetSelector: '[data-tour="receitas-filtros"]',
        title: 'Filtros',
        content: 'Filtre por período, status de pagamento e forma.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'receitas-4',
        targetSelector: '[data-tour="receitas-registrar"]',
        title: 'Registrar Pagamento',
        content: 'Adicione pagamento a um agendamento existente.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-despesas',
    name: 'Despesas',
    description: 'Gestão de gastos',
    icon: 'TrendingDown',
    estimatedTime: '2 min',
    requiredRoute: '/admin/financeiro/despesas',
    steps: [
      {
        id: 'despesas-1',
        targetSelector: '[data-tour="despesas-nova"]',
        title: 'Nova Despesa',
        content: 'Cadastre gastos operacionais do negócio.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'despesas-2',
        targetSelector: '[data-tour="despesas-total"]',
        title: 'Total de Despesas',
        content: 'Soma de todas as despesas do período selecionado.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'despesas-3',
        targetSelector: '[data-tour="despesas-filtros"]',
        title: 'Filtros',
        content: 'Filtre por categoria, período e status.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'despesas-4',
        targetSelector: '[data-tour="despesas-tabela"]',
        title: 'Lista de Despesas',
        content: 'Todas as despesas com ações de edição e exclusão.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-fluxo',
    name: 'Fluxo de Caixa',
    description: 'Projeção financeira',
    icon: 'LineChart',
    estimatedTime: '2 min',
    requiredRoute: '/admin/financeiro/fluxo-caixa',
    steps: [
      {
        id: 'fluxo-1',
        targetSelector: '[data-tour="fluxo-grafico"]',
        title: 'Gráfico de Projeção',
        content: 'Visualize entradas e saídas futuras.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'fluxo-2',
        targetSelector: '[data-tour="fluxo-saldo"]',
        title: 'Saldo Projetado',
        content: 'Estimativa de saldo ao final do período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'fluxo-3',
        targetSelector: '[data-tour="fluxo-lancamentos"]',
        title: 'Lançamentos Previstos',
        content: 'Lista de entradas e saídas programadas.',
        action: 'view',
        position: 'top',
      },
      {
        id: 'fluxo-4',
        targetSelector: '[data-tour="fluxo-periodo"]',
        title: 'Horizonte',
        content: 'Ajuste o horizonte da projeção: 7, 15 ou 30 dias.',
        action: 'click',
        position: 'left',
      },
    ],
  },
  
  {
    id: 'screen-metas',
    name: 'Metas Financeiras',
    description: 'Objetivos e progresso',
    icon: 'Target',
    estimatedTime: '2 min',
    requiredRoute: '/admin/financeiro/metas',
    steps: [
      {
        id: 'metas-1',
        targetSelector: '[data-tour="metas-nova"]',
        title: 'Nova Meta',
        content: 'Defina objetivos financeiros mensais.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'metas-2',
        targetSelector: '[data-tour="metas-progresso"]',
        title: 'Progresso da Meta',
        content: 'Visualize quanto falta para atingir a meta.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'metas-3',
        targetSelector: '[data-tour="metas-barra"]',
        title: 'Barra de Progresso',
        content: 'Percentual alcançado da meta atual.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'metas-4',
        targetSelector: '[data-tour="metas-historico"]',
        title: 'Histórico',
        content: 'Metas anteriores e resultados alcançados.',
        action: 'view',
        position: 'top',
      },
    ],
  },

  // ═══════════════════════════════════════════════════
  // MÓDULO INTEGRAÇÕES
  // ═══════════════════════════════════════════════════
  
  {
    id: 'screen-whatsapp-config',
    name: 'Config WhatsApp',
    description: 'Conexão e automação',
    icon: 'MessageCircle',
    estimatedTime: '2 min',
    requiredRoute: '/admin/integracoes/whatsapp-config',
    steps: [
      {
        id: 'whatsconfig-1',
        targetSelector: '[data-tour="whatsconfig-numero"]',
        title: 'Número Conectado',
        content: 'Status da conexão do seu WhatsApp Business.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'whatsconfig-2',
        targetSelector: '[data-tour="whatsconfig-templates"]',
        title: 'Templates',
        content: 'Gerencie modelos de mensagem para automações.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'whatsconfig-3',
        targetSelector: '[data-tour="whatsconfig-auto"]',
        title: 'Automações',
        content: 'Configure envios automáticos por evento.',
        action: 'view',
        position: 'right',
      },
    ],
  },
  
  {
    id: 'screen-whatsapp-despesas',
    name: 'Despesas WhatsApp',
    description: 'Custos de mensagens',
    icon: 'Receipt',
    estimatedTime: '1 min',
    requiredRoute: '/admin/integracoes/whatsapp-despesas',
    steps: [
      {
        id: 'whatsdespesas-1',
        targetSelector: '[data-tour="whatsdespesas-total"]',
        title: 'Custo Total',
        content: 'Gasto total com envio de mensagens no período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'whatsdespesas-2',
        targetSelector: '[data-tour="whatsdespesas-por-tipo"]',
        title: 'Por Tipo',
        content: 'Custo separado por tipo de mensagem.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'whatsdespesas-3',
        targetSelector: '[data-tour="whatsdespesas-evolucao"]',
        title: 'Evolução',
        content: 'Gráfico de evolução dos custos ao longo do tempo.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-anuncios',
    name: 'Anúncios',
    description: 'Meta/Google Ads',
    icon: 'Megaphone',
    estimatedTime: '2 min',
    requiredRoute: '/admin/integracoes/anuncios',
    steps: [
      {
        id: 'anuncios-1',
        targetSelector: '[data-tour="anuncios-conectar"]',
        title: 'Conectar Conta',
        content: 'Conecte sua conta de anúncios do Facebook/Meta.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'anuncios-2',
        targetSelector: '[data-tour="anuncios-metricas"]',
        title: 'Métricas de Campanha',
        content: 'Impressões, cliques, CTR e custo por conversão.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'anuncios-3',
        targetSelector: '[data-tour="anuncios-roas"]',
        title: 'ROAS',
        content: 'Retorno sobre investimento em anúncios.',
        action: 'view',
        position: 'right',
      },
    ],
  },
  
  {
    id: 'screen-pixel',
    name: 'Facebook Pixel',
    description: 'Tracking de conversões',
    icon: 'Activity',
    estimatedTime: '2 min',
    requiredRoute: '/admin/integracoes/pixel',
    steps: [
      {
        id: 'pixel-1',
        targetSelector: '[data-tour="pixel-status"]',
        title: 'Status da Conexão',
        content: 'Verde = pixel conectado e rastreando eventos.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'pixel-2',
        targetSelector: '[data-tour="pixel-pageviews"]',
        title: 'Page Views',
        content: 'Total de visualizações de página rastreadas.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'pixel-3',
        targetSelector: '[data-tour="pixel-compras"]',
        title: 'Conversões de Compra',
        content: 'Compras registradas e enviadas ao Meta.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'pixel-4',
        targetSelector: '[data-tour="pixel-debug"]',
        title: 'Ferramentas de Debug',
        content: 'Expanda para ver configurações e debug do pixel.',
        action: 'click',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-webhook',
    name: 'Webhooks',
    description: 'APIs externas',
    icon: 'Webhook',
    estimatedTime: '2 min',
    requiredRoute: '/admin/integracoes/webhook',
    steps: [
      {
        id: 'webhook-1',
        targetSelector: '[data-tour="webhook-novo"]',
        title: 'Novo Webhook',
        content: 'Configure integração com sistemas externos.',
        action: 'click',
        position: 'bottom',
      },
      {
        id: 'webhook-2',
        targetSelector: '[data-tour="webhook-lista"]',
        title: 'Webhooks Configurados',
        content: 'Lista de webhooks ativos e seus status.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'webhook-3',
        targetSelector: '[data-tour="webhook-eventos"]',
        title: 'Eventos',
        content: 'Tipos de eventos que disparam o webhook.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'webhook-4',
        targetSelector: '[data-tour="webhook-logs"]',
        title: 'Logs',
        content: 'Histórico de chamadas e respostas.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-whatsapp-dashboard',
    name: 'Dashboard WhatsApp',
    description: 'Métricas de mensagens',
    icon: 'MessageSquare',
    estimatedTime: '2 min',
    requiredRoute: '/admin/whatsapp-dashboard',
    steps: [
      {
        id: 'whatsdash-1',
        targetSelector: '[data-tour="whatsdash-enviadas"]',
        title: 'Mensagens Enviadas',
        content: 'Total de mensagens enviadas no período.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'whatsdash-2',
        targetSelector: '[data-tour="whatsdash-taxa"]',
        title: 'Taxa de Entrega',
        content: 'Percentual de mensagens entregues com sucesso.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'whatsdash-3',
        targetSelector: '[data-tour="whatsdash-conversas"]',
        title: 'Conversas Ativas',
        content: 'Número de conversas em andamento.',
        action: 'view',
        position: 'bottom',
      },
      {
        id: 'whatsdash-4',
        targetSelector: '[data-tour="whatsdash-grafico"]',
        title: 'Evolução',
        content: 'Gráfico de mensagens ao longo do tempo.',
        action: 'view',
        position: 'top',
      },
    ],
  },
  
  {
    id: 'screen-perfil',
    name: 'Meu Perfil',
    description: 'Dados pessoais',
    icon: 'User',
    estimatedTime: '1 min',
    requiredRoute: '/admin/perfil',
    steps: [
      {
        id: 'perfil-1',
        targetSelector: '[data-tour="perfil-foto"]',
        title: 'Foto de Perfil',
        content: 'Clique na foto para alterar. Máximo 2MB.',
        action: 'click',
        position: 'right',
      },
      {
        id: 'perfil-2',
        targetSelector: '[data-tour="perfil-dados"]',
        title: 'Dados Pessoais',
        content: 'Edite nome, telefone, cargo e endereço.',
        action: 'view',
        position: 'right',
      },
      {
        id: 'perfil-3',
        targetSelector: '[data-tour="perfil-salvar"]',
        title: 'Salvar Alterações',
        content: 'Sempre clique em salvar após fazer alterações.',
        action: 'click',
        position: 'top',
      },
    ],
  },
];

/**
 * Busca um tour de tela pela rota
 */
export const getScreenTourByRoute = (route: string): Tour | undefined => {
  // Normaliza a rota removendo trailing slash
  const normalizedRoute = route.endsWith('/') ? route.slice(0, -1) : route;
  return SCREEN_TOURS.find(tour => tour.requiredRoute === normalizedRoute);
};

/**
 * Busca um tour de tela pelo ID
 */
export const getScreenTourById = (id: string): Tour | undefined => {
  return SCREEN_TOURS.find(tour => tour.id === id);
};

/**
 * Retorna todas as rotas que possuem tours de tela
 */
export const getScreenTourRoutes = (): string[] => {
  return SCREEN_TOURS.map(tour => tour.requiredRoute);
};
